name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: wget -O - "http://dumpscript.epitest.eu" | sudo bash -s
    - name: Unit Tests
      run: make tests_run
